### ISSUE TITLE
Indicate that mDNS obfuscation only needs to be done for private IPs

### ISSUE THREAD

**Issue by juberti** [youennf/mdns-ice-candidates#31]

**Comment by tQsW** [comment]
If we add this indication, do we also need to clarify the use case for lite ICE agents?

**Comment by tQsW** [comment]
{{#gathering}} starts with "For any host candidate gathered by an ICE agent as part of {{RFC8445}} section 5.1.1," it seems the place we need to revise to resolve this issue. I was thinking of allowing ICE lite implementation to skip the mDNS wrapping, since lite agents only use host candidates (8445, section 2.5). The lite implementation is however not required restricted to ICE agents that always have public IPs from my reading of that section, but rather an alternative to simplify the implementation when possible. So I am still not sure if it makes sense to say lite ICE can be exempted from wrapping; or instead indicating mDNS wrapping can be skipped if host candidates are equivalent to srflx candidates, and automatically the intended use of lite ICE satisfies this condition.

**Comment by juberti** [comment]
Right, the public IPs exception probably covers this. #32 also indicates that this is really for web browsers, which are not allowed to implement ICE Lite.

**Comment by juberti** [comment]
Partially addressed in #62, will probably include some additional clarifying text once it lands
